mocap_optitrack_driver_node:
  ros__parameters:
    connection_type: "Unicast" # Unicast / Multicast
    server_address: "192.168.0.9" # "192.168.112.1"
    local_address: "192.168.0.6"
    multicast_address: "239.255.42.99"
    server_command_port: 1510
    server_data_port: 1511

    lastFrameNumber: 0
    frameCount: 0
    droppedFrameCount: 0
    n_markers: 0
    n_unlabeled_markers: 0
    qos_history_policy: "keep_all"         # keep_all / keep_last
    qos_reliability_policy: "best_effort"  # best_effort / reliable
    qos_depth: 10                          # 10 / 100 / 1000
    natnet_version: ""                     # optionally requests specific version of data bitstream
                                           # can be left blank "" or with 4 digit version i.e "4.1.0.0"
    
    pub_PoseStamped_topics: true
    pub_PoseWithCovarianceStamped_topics: true
    pub_mocap_msgs_rigid_bodies_topic: true
    pub_mocap_msgs_markers_topic: true

    # only used with PoseWithCovarianceStamped topics
    positional_variance: 0.001 # in meters
    rotational_variance: 0.0015 # in radians
    
    # publish_y_up_tf creates A static transform from XY ground plane Z up to ZX ground plane Y up
    # This allows for visualization to match motive output
    # This new transform has a child that is the rb_parent_frame_name frame of reference
    publish_y_up_tf: true
    y_up_frame_name: "map"
    publish_tf: true
    rb_parent_frame_name: "optitrack"
    rigid_bodies:
      1:
        name: "base_link"
      2:
        name: "end_effector"
